SitioPCFull/Controllers/CarritoController.cs
using SitioPCFull.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IdentitySample.Models;
using Microsoft.AspNet.Identity;

namespace SitioPCFull.Controllers
{
    public class CarritoController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [HttpPost]
        public JsonResult AgregaCarrito(int? id, int cantidad)
        {
            if (Session["carrito"] == null)
            {
                List<CarritoItem> compras = new List<CarritoItem>();
                compras.Add(new CarritoItem(db.productos.Find(id), cantidad));
                Session["carrito"] = compras;
            }
            else
            {
                List<CarritoItem> compras = (List<CarritoItem>)Session["carrito"];
                int IndexExistente = getIndex(id);
                if (IndexExistente == -1)
                {
                    compras.Add(new CarritoItem(db.productos.Find(id), cantidad));
                }
                else
                {
                    compras[IndexExistente].Cantidad += cantidad;
                    Session["carrito"] = compras;
                }
            }
            return Json(new { response = true }, JsonRequestBehavior.AllowGet);
        }

        // GET: Carrito
        //Agregar productos a la lista de carrito
        [HttpGet]
        public ActionResult AgregaCarrito()
        {
            return View();
        }

        //Eliminar un producto de la lista de carrito
        public ActionResult Delete(int? id)
        {
            List<CarritoItem> compras = (List<CarritoItem>)Session["carrito"];
            compras.RemoveAt(getIndex(id));

            return View("AgregaCarrito");
        }

        [Authorize(Roles = "Cliente"), RequireHttps]
        //Logica para finalizar la compra del cliente
        public ActionResult FinalizaCompra()
        {
            List<CarritoItem> compras = (List<CarritoItem>)Session["carrito"];
            if (compras != null && compras.Count > 0)
            {
                venta nuevaVenta = new venta();
                nuevaVenta.fecha = DateTime.Now;
                nuevaVenta.ApplicationUserId = User.Identity.GetUserId();
                nuevaVenta.total = compras.Sum(x => x.Producto.precio * x.Cantidad);

                nuevaVenta.ventadetalle = (from producto in compras
                                           select new ventadetalle
                                           {
                                               productosId = producto.Producto.Id,
                                               nombre = producto.Producto.nombre,
                                               cantidad = producto.Cantidad,
                                               precio = producto.Producto.precio,
                                               subtotal = producto.Cantidad * producto.Producto.precio
                                           }).ToList();

                db.venta.Add(nuevaVenta);
                db.SaveChanges();
                Session["carrito"] = new List<CarritoItem>();
            }

            return View();
        }

        //Traer index para saber si ya existe el producto en la lista de carrito
        private int getIndex(int? id)
        {
            List<CarritoItem> compras = (List<CarritoItem>)Session["carrito"];
            for (int i = 0; i < compras.Count; i++)
            {
                if (compras[i].Producto.Id == id)
                {
                    return i;
                }
            }
            return -1;
        }
    }
}

SitioPCFull/Controllers/UserAdminController.cs
using IdentitySample.Models;
using Microsoft.AspNet.Identity.Owin;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
//
using System;
using System.Collections.Generic;
using System.Data;
using SitioPCFull.Models;
using SitioPCFull.ViewModels;

namespace IdentitySample.Controllers
{
    [Authorize(Roles = "Admin"), RequireHttps]
    public class UsersAdminController : Controller
    {
        public UsersAdminController()
        {
        }

        public UsersAdminController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Users/
        [HttpGet]
        public ActionResult Index(int pagina = 1)
        {
            var cantidadRegistrosPorPagina = 5;
            using (var db = new ApplicationDbContext())
            {
                var personas = db.Users.OrderBy(x => x.Id)
                        .Skip((pagina - 1) * cantidadRegistrosPorPagina)
                        .Take(cantidadRegistrosPorPagina).ToList();
                var totalDeRegistros = db.Users.Count();

                var modelo = new IndexViewModelPag();
                modelo.Personas = personas;
                modelo.PaginaActual = pagina;
                modelo.TotalDeRegistros = totalDeRegistros;
                modelo.RegistrosPorPagina = cantidadRegistrosPorPagina;

                return View(modelo);
            }
        }
        /*public async Task<ActionResult> Index()
        {
            
            return View(await UserManager.Users.ToListAsync());
        }*/

        //
        // GET: /Users/Details/5
        [HttpGet]
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);

            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);

            return View(user);
        }

        //
        // GET: /Users/Create
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            //Get the list of Roles
            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
            return View();
        }

        //
        // POST: /Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = userViewModel.UserName, Email = userViewModel.Email,
                    Nombre = userViewModel.Nombre,
                    Apellidos = userViewModel.Apellidos,
                    Direccion = userViewModel.Direccion,
                    Colonia = userViewModel.Colonia,
                    Region = userViewModel.Region,
                    CP = userViewModel.CP,
                    Telefono = userViewModel.Telefono};

                var adminresult = await UserManager.CreateAsync(user, userViewModel.Password);

                //Add User to the selected Roles 
                if (adminresult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await UserManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", adminresult.Errors.First());
                    ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
                    return View();

                }
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
            return View();
        }

        //
        // GET: /Users/Edit/1
        [HttpGet]
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var userRoles = await UserManager.GetRolesAsync(user.Id);

            return View(new EditUserViewModel()
            {
                Id = user.Id,
                Nombre = user.Nombre,
                Apellidos = user.Apellidos,
                UserName = user.UserName,
                Email = user.Email,
                Direccion = user.Direccion,
                Colonia = user.Colonia,
                Region = user.Region,
                CP = user.CP,
                Telefono = user.Telefono,
                RolesList = RoleManager.Roles.ToList().Select(x => new SelectListItem()
                {
                    Selected = userRoles.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                })
            });
        }

        //
        // POST: /Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Nombre,Apellidos,Direccion,Colonia,Region,CP,Telefono,Email,UserName,Id")] EditUserViewModel editUser, params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }

                user.Nombre = editUser.Nombre;
                user.Apellidos = editUser.Apellidos;
                user.UserName = editUser.UserName;
                user.Email = editUser.Email;
                user.Direccion = editUser.Direccion;
                user.Colonia = editUser.Colonia;
                user.Region = editUser.Region;
                user.CP = editUser.CP;
                user.Telefono = editUser.Telefono;

                var userRoles = await UserManager.GetRolesAsync(user.Id);

                selectedRole = selectedRole ?? new string[] { };

                var result = await UserManager.AddToRolesAsync(user.Id, selectedRole.Except(userRoles).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                result = await UserManager.RemoveFromRolesAsync(user.Id, userRoles.Except(selectedRole).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Something failed.");
            return View();
        }

        //
        // GET: /Users/Delete/5
        [HttpGet]
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //
        // POST: /Users/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var user = await UserManager.FindByIdAsync(id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                var result = await UserManager.DeleteAsync(user);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

SitioPCFull/Controllers/ventaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IdentitySample.Models;
using SitioPCFull.Models;
using Microsoft.AspNet.Identity;

namespace SitioPCFull.Controllers
{

    public class ventaController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: venta
        public ActionResult Index()
        {
            return View(db.venta.ToList().OrderBy(x => x.fecha));
        }

        //MisCompras
        [Authorize(Roles = "Cliente"), RequireHttps]
        public ActionResult MisCompras()
        {
            var usrId = User.Identity.GetUserId();
            var cm = db.venta.Where(x => x.ApplicationUserId == usrId);
            return View(cm.ToList());
        }

        // GET: ventas/Details/5
        public ActionResult Details(int? id)
        {
            return View(db.venta.Find(id));
        }
    }
}

SitioPCFull/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MundoPC</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/styles.css")
    @Styles.Render("~/Img/png")
    @Styles.Render("~/Img/jpg")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body class="fondo-body">
    <nav class="navbar navbar-expand-xl navbar-dark text-white sticky-top bgnav">
        <a href='@Url.Action("Index","Home")' class="navbar-brand text-white font-weight-bold shadow-logo text-danger">MundoPC</a>
        <button class="navbar-toggler btn-outline-secondary" data-target="#menu" data-toggle="collapse" type="button">
            <span class="navbar-toggler-icon align-items-center"></span>
        </button>
        <div class="collapse navbar-collapse" id="menu">
            <ul class="navbar-nav mr-auto layout">
                @if (!User.IsInRole("Admin"))
                {
                    <li class="nav-item active"><a href='@Url.Action("Lista", "productos")' class="text-white nav-link hoverli">Productos</a></li>
                    if (Session["carrito"] != null)
                    {
                        <li class="nav-item active"><a href='@Url.Action("AgregaCarrito", "Carrito")' class="text-white nav-link voverli">Carrito</a></li>
                    }
                }
                @if (Request.IsAuthenticated && User.IsInRole("Cliente"))
                {
                    <li class="nav-item active"><a href='@Url.Action("MisCompras", "venta")' class="text-white nav-link hoverli">Mis compras</a></li>

                }
                @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <li class="nav-item active"><a href='@Url.Action("Index", "RolesAdmin")' class="text-white nav-link hoverli">Adminstrar Roles</a></li>
                    <li class="nav-item active"><a href='@Url.Action("Index", "UsersAdmin")' class="text-white nav-link hoverli">Administrar Usuarios</a></li>
                    <li class="nav-item active"><a href='@Url.Action("Index", "productos")' class="text-white nav-link hoverli">Administrar Productos</a></li>
                    <li class="nav-item active"><a href='@Url.Action("Index", "venta")' class="text-white nav-link hoverli">Administrar Ventas</a></li>
                    @*<li class="nav-item active"><a href='@Url.Action("Index", "UsersAdmin")' class="text-white nav-link hoverli">Pedidos </a></li>*@
                }
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </nav>
    @RenderBody()
    <div class="shadow-lg pt-4">
        <footer class="footer text-center text-light">
            <p>MundoPC &copy; @DateTime.Now.Year - Todos los derechos reservados</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SitioPCFull/Views/Shared/_paginador.cshtml
@model SitioPCFull.Models.BaseModelo
@{
   var cantidadPaginas = (int)Math.Ceiling((double)Model.TotalDeRegistros / Model.RegistrosPorPagina);

    int Inicial = 1;
    var radio = 3;
    var cantidadMaximaDePaginas = radio * 2 + 1;
    int Final = (cantidadPaginas > cantidadMaximaDePaginas) ? cantidadMaximaDePaginas : cantidadPaginas;
    if (Model.PaginaActual > radio + 1)
    {
        Inicial = Model.PaginaActual - radio;
        if (cantidadPaginas > Model.PaginaActual + radio)
        {
            Final = Model.PaginaActual + radio;
        }
        else
        {
            Final = cantidadPaginas;
        }
    }
}

    <ul class="pagination pagination-sm">

        <li class="page-item">@Html.ActionLink("Primera", null, new { pagina = 1 }, new { @class = "page-link" })</li>
        @for (int i = Inicial; i <= Final; i++)
        {

            if (i == Model.PaginaActual)
            {
                <li class="page-item active">@Html.ActionLink(i.ToString(), null, new { pagina = i }, new { @class = "page-link" })</li>
            }
            else
            {
                <li class="page-item">@Html.ActionLink(i.ToString(), null, new { pagina = i }, new { @class = "page-link" })</li>
            }
        }

        <li class="page-item">@Html.ActionLink("Ultima", null, new { pagina = cantidadPaginas }, new { @class = "page-link" })</li>
    </ul>